export type admin = {
  id: number;
  first_name: string;
  last_name: string;
  email: string;
  is_deleted: number;
  deleted_at: string;
  created_at: string;
  updated_at: string;
  role_id: number;
  phone: string;
  department: string;
  profile_photo: string;
  status: string;
  join_date: string;
  dob: string;
  address: string;
  state: string;
  country: string;
  shift_day: string;
  shift_hour: string;
};
