export type bookingsists = {
  id: string;
  customerName: string;
  apartnmentName: string;
  bookingDate: string;
  amount: string;
  exchangeRate: string;
  checkIn: string;
  checkOut: string;
  status: string;
}[];

export type bookingsById = {
  id: number;
  booking_number: string;
  shortlet_id: number;
  user_id: number;
  check_in_date: string;
  check_out_date: string;
  check_in_time: string;
  check_out_time: string;
  number_of_days: number;
  number_of_guests: number;
  guest_breakdown: string;
  currency: string;
  caution_fee: number;
  tax_fee: number;
  base_price: number;
  discount_fee: number;
  total_price: number;
  exchange_rate: string;
  caution_fee_NGN: number;
  tax_fee_NGN: number;
  base_price_NGN: number;
  discount_amount_NGN: number;
  total_price_NGN: number;
  status: string;
  payment_status: string;
  payment_method: string;
  promo_code: string;
  notes: string;
  channel: string;
  payment_expires_at: string;
  is_deleted: number;
  deleted_at: string;
  created_at: string;
  updated_at: string;
  transferred_from: string;
  transferred_to: string;
  visitor_code: string;
  account_name: string;
  account_number: string;
  bank_name: string;
  has_requested_refund: number;
  shortlet: {
    id: number;
    name: string;
    slug: string;
    description: string;
    location: string;
    currency: string;
    price: number;
    caution_fee: number;
    tax_fee: number;
    no_of_bedrooms: number;
    no_of_bathrooms: number;
    min_guests: string;
    max_guests: number;
    point_of_interest: string;
    cancellation_policy: string;
    availability_status: string;
    is_deleted: number;
    deleted_at: string;
    created_at: string;
    updated_at: string;
    room_option_id: number;
    city: string;
    state: string;
    country: string;
    longitude: string;
    latitude: string;
    location_group_id: string;
  };
};

export type bookingHistory = {
  id: number;
  user_id: number;
  admin_id: number;
  booking_id: number;
  name: string;
  user_type: string;
  action_type: string;
  message: string;
  is_deleted: number;
  deleted_at: string;
  created_at: string;
  updated_at: string;
}[];

export type bookingsByUserId = {
  id: number;
  booking_number: string;
  shortlet_id: number;
  user_id: number;
  check_in_date: string;
  check_out_date: string;
  check_in_time: string;
  check_out_time: string;
  number_of_days: number;
  number_of_guests: number;
  guest_breakdown: string;
  currency: string;
  caution_fee: number;
  tax_fee: number;
  base_price: number;
  discount_fee: string;
  total_price: number;
  exchange_rate: string;
  caution_fee_NGN: number;
  tax_fee_NGN: number;
  base_price_NGN: number;
  discount_amount_NGN: string;
  total_price_NGN: number;
  status: string;
  payment_status: string;
  payment_method: string;
  promo_code: string;
  notes: string;
  channel: string;
  payment_expires_at: string;
  is_deleted: 0 | 1;
  deleted_at: string;
  created_at: string;
  updated_at: string;
  transferred_from: string;
  transferred_to: string;
  visitor_code: string;
  account_name: string;
  account_number: string;
  bank_name: string;
  has_requested_refund: 0 | 1;
  shortlet: {
    id: number;
    name: string;
  };
}[];
