export type coupons = {
  id: number;
  code: string;
  start_date: string;
  end_date: string;
  applicable_to_shortlet: string;
  applicable_to_user: string;
  type: string;
  validity: string;
  is_reusable: number;
  applicable_shortlets: { id: string; name: string }[];
  applicable_users: { id: string; name: string }[];
  price: number;
  percentage: number;
  currency: string;
  minimum_amount: number;
  maximum_amount: number;
  is_active: number;
  is_deleted: number;
  deleted_at: string;
  created_by: string;
  deleted_by: string;
  created_at: string;
  updated_at: string;
  applicable_shortlet_count: number;
  applicable_user_count: number;
};
