export type customersists = {
  id: string;
  firstname: string;
  lastname: string;
  phoneNumber: string;
  country: string;
  bookings: string;
}[];

export type customersById = {
  id: string;
  firstname: string;
  lastname: string;
  email: string;
  phoneNumber: string;
  profileImg: string;
  gender: string;
  dob: string;
  country: string;
  state: string;
  city: string;
  address: string;
  placeOfBirth: string;
  idType: string;
  idNumber: string;
  idImage: string;
  pinGenerated: string;
  notes: string;
  companyName: string;
  VATid: string;
  companyEmail: string;
  companyId: string;
  companyCountry: string;
  companyState: string;
  companyCity: string;
  companyAddress: string;
  isSalesChannel: boolean;
  salesChannelName: string;
  salesChannelCommision: string;
  calculateCommissionOn: string;
  applyCommissionOn: string;
};
